name: E2E Tests

on:
  deployment_status:
jobs:
  run-e2es:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'deployment_status' &&
      github.event.deployment_status.state == 'success'
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Check environment URL
        id: check_env
        run: |
          if [[ "${{ github.event.deployment_status.environment_url }}" == *"v4-testnet"* || "${{ github.event.deployment_status.environment_url }}" == *"v4-staging"* ]]; then
            echo "environment_url_matches=true" >> $GITHUB_ENV
          else
            echo "environment_url_matches=false" >> $GITHUB_ENV
            echo "This deployment does not require E2E tests. Exiting..."
            exit 0 # Exits the job successfully without running the subsequent steps
          fi

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: dydxprotocol/setup-pnpm@v1

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm install --loglevel warn

      - name: Run e2e tests
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          E2E_ENVIRONMENT_PASSWORD: ${{ secrets.E2E_ENVIRONMENT_PASSWORD }}
          E2E_ENVIRONMENT_URL: ${{ github.event.deployment_status.environment_url }}
        run: pnpm run wdio
